export default {
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_DETAILED_USER: 'FETCH_DETAILED_USER',
  GET_LOGGED_IN_USER: 'GET_LOGGED_IN_USER',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
  USER_LOGOUT: 'USER_LOGOUT',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  NULL_LOGIN_ERROR_MESSAGE: 'NULL_LOGIN_ERROR_MESSAGE',
  NULL_REGISTER_ERROR_MESSAGE: 'NULL_REGISTER_ERROR_MESSAGE',
};
