export default {
  FETCH_ARTICLES: 'FETCH_ARTICLES',
  FETCH_META: 'FETCH_META',
  CHANGE_LOADING_STATE: 'CHANGE_LOADING_STATE',
  SET_ACTIVE_ARTICLE: 'SET_ACTIVE_ARTICLE',
  CREATE_NEW_CATEGORY: 'CREATE_NEW_CATEGORY',
  SET_CREATION_ERROR: 'SET_CREATION_ERROR',
  SET_FEATURED_IMAGE: 'SET_FEATURED_IMAGE',
};
